name: Windows (Stable)

on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: Override version tag
      enable_mangling:
        description: Enable mangling (longer compilation)
        type: boolean
        required: true
        default: true
      build_command_line:
        description: Build command-line tools
        type: boolean
        required: true
        default: true
      build_zip:
        description: Build ZIP
        type: boolean
        required: true
        default: true
      build_msi:
        description: Build MSI
        type: boolean
        required: true
        default: true
      build_system_exe:
        description: Build system-wide installer
        type: boolean
        required: true
        default: true
      build_user_exe:
        description: Build user-wide installer
        type: boolean
        required: true
        default: true

env:
  APP_NAME: VSCodium
  ASSETS_REPOSITORY: ${{ github.repository }}
  BINARY_NAME: codium
  GH_REPO_PATH: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  OS_NAME: windows
  VSCODE_QUALITY: stable
  RELEASE_VERSION: ${{ github.event.inputs.version_tag }}
  SHOULD_BUILD_ZIP: ${{ github.event.inputs.build_zip == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_EXE_SYS: ${{ github.event.inputs.build_system_exe == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_EXE_USR: ${{ github.event.inputs.build_user_exe == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_MSI: ${{ github.event.inputs.build_msi == 'true' && 'yes' || 'no' }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      MS_COMMIT: ${{ env.MS_COMMIT }}
      MS_TAG: ${{ env.MS_TAG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: Clone VSCode repo
        run: ./get_repo.sh

  compile:
    needs:
      - check
    runs-on: ubuntu-20.04
    env:
      MS_COMMIT: ${{ needs.check.outputs.MS_COMMIT }}
      MS_TAG: ${{ needs.check.outputs.MS_TAG }}
      RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
      VSCODE_ARCH: 'x64'
    outputs:
      BUILD_SOURCEVERSION: ${{ env.BUILD_SOURCEVERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x64

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.2'

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kerberos
        run: sudo apt-get update -y && sudo apt-get install -y libkrb5-dev

      - name: Clone VSCode repo
        run: ./get_repo.sh

      - name: Build
        env:
          NO_MANGLING: ${{ github.event.inputs.enable_mangling == 'true' && 'no' || 'yes' }}
        run: ./build.sh

      - name: Compress sources artifact
        run: |
          find vscode -type f -not -path "*/node_modules/*" -not -path "vscode/.build/node/*" -not -path "vscode/.git/*" > vscode.txt
          echo "vscode/.build/extensions/node_modules" >> vscode.txt
          echo "vscode/.git" >> vscode.txt
          tar -czf vscode.tar.gz -T vscode.txt

      - name: Upload sources artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sources
          path: ./vscode.tar.gz
          retention-days: 1

  build:
    needs:
      - check
      - compile
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - vscode_arch: x64
            cargo_toolchain: x86_64
          - vscode_arch: arm64
            cargo_toolchain: aarch64
    defaults:
      run:
        shell: bash
    env:
      BUILD_SOURCEVERSION: ${{ needs.compile.outputs.BUILD_SOURCEVERSION }}
      MS_COMMIT: ${{ needs.check.outputs.MS_COMMIT }}
      MS_TAG: ${{ needs.check.outputs.MS_TAG }}
      RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.2'

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup OpenSSL
        run: |
          export VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT
          vcpkg install openssl:${{ matrix.vscode_arch }}-windows-static
        if: ${{ (matrix.cargo_toolchain != 'none') && (github.event.inputs.build_command_line == 'true') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.cargo_toolchain }}-pc-windows-msvc
        if: ${{ (matrix.cargo_toolchain != 'none') && (github.event.inputs.build_command_line == 'true') }}

      - name: Download sources artifact
        uses: actions/download-artifact@v4
        with:
          name: Sources

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TOOLCHAIN: ${{ (github.event.inputs.build_command_line == 'true' && matrix.cargo_toolchain != 'none') && matrix.cargo_toolchain || 'none' }}
          RUST_TARGET: ${{ matrix.cargo_toolchain }}-pc-windows-msvc
          npm_config_arch: ${{ matrix.vscode_arch }}
          npm_config_target_arch: ${{ matrix.vscode_arch }}
        run: ./build/windows/package.sh

      - name: Prepare assets
        run: ./prepare_assets.sh

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: VSCodium-${{ matrix.vscode_arch }}
          path: assets/
          retention-days: 3
