name: MacOS (Stable)

on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: Override version tag
      enable_mangling:
        description: Enable mangling (longer compilation)
        type: boolean
        required: true
        default: true
      build_cli:
        description: Build separate command-line utility
        type: boolean
        required: true
        default: true
      build_zip:
        description: Build ZIP
        type: boolean
        required: true
        default: true
      build_dmg:
        description: Build DMG
        type: boolean
        required: true
        default: true
      build_src:
        description: Build source
        type: boolean
        required: true
        default: false

env:
  APP_NAME: VSCodium
  ASSETS_REPOSITORY: ${{ github.repository }}
  BINARY_NAME: codium
  GH_REPO_PATH: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  OS_NAME: osx
  VSCODE_QUALITY: stable
  RELEASE_VERSION: ${{ github.event.inputs.version_tag }}
  SHOULD_BUILD_ZIP: ${{ github.event.inputs.build_zip == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_DMG: ${{ github.event.inputs.build_dmg == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_SRC: ${{ github.event.inputs.build_src == 'true' && 'yes' || 'no' }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    env:
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-13
            vscode_arch: x64
#          - runner: [self-hosted, macOS, ARM64]
#            vscode_arch: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: env.VSCODE_ARCH == 'x64'

      - name: Clone VSCode repo
        run: . get_repo.sh

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_MANGLING: ${{ github.event.inputs.enable_mangling == 'true' && 'no' || 'yes' }}
        run: ./build.sh

      - name: Prepare assets
        env:
          CERTIFICATE_OSX_APP_PASSWORD: ${{ secrets.CERTIFICATE_OSX_NEW_APP_PASSWORD }}
          CERTIFICATE_OSX_ID: ${{ secrets.CERTIFICATE_OSX_NEW_ID }}
          CERTIFICATE_OSX_P12_DATA: ${{ secrets.CERTIFICATE_OSX_NEW_P12_DATA }}
          CERTIFICATE_OSX_P12_PASSWORD: ${{ secrets.CERTIFICATE_OSX_NEW_P12_PASSWORD }}
          CERTIFICATE_OSX_TEAM_ID: ${{ secrets.CERTIFICATE_OSX_NEW_TEAM_ID }}
          SHOULD_BUILD_CLI: ${{ github.event.inputs.build_cli == 'true' && 'yes' || 'no' }}
        run: ./prepare_assets.sh

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: VSCodium-${{ matrix.vscode_arch }}
          path: assets/
          retention-days: 3

      - name: Clean up keychain
        if: always()
        run: |
          KEYCHAIN=$RUNNER_TEMP/build.keychain

          if [ -f "$KEYCHAIN" ];
          then
            security delete-keychain $KEYCHAIN
          fi
