name: Build Windows (Stable)

on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: Override version tag
      build_update:
        description: Build the auto updater
        type: boolean
        required: true
        default: false
      build_reh:
        description: Build the remote extension host
        type: boolean
        required: true
        default: false
      build_cli:
        description: Build separate command-line utility
        type: boolean
        required: true
        default: false
      build_zip:
        description: Build ZIP
        type: boolean
        required: true
        default: true
      build_msi:
        description: Build MSI
        type: boolean
        required: true
        default: true
      build_system_exe:
        description: Build system-wide installer
        type: boolean
        required: true
        default: true
      build_user_exe:
        description: Build user-wide installer
        type: boolean
        required: true
        default: true
      upload_assets:
        description: Upload assets (artifacts)
        type: boolean
        required: true
        default: true
      release_assets:
        description: Release assets (draft)
        type: boolean
        required: true
        default: false

env:
  APP_NAME: VSCodium
  ASSETS_REPOSITORY: ${{ github.repository }}
  BINARY_NAME: codium
  DISABLE_UPDATE: ${{ github.event.inputs.build_update == 'true' && 'no' || 'yes' }}
  GH_REPO_PATH: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  OS_NAME: windows
  VSCODE_QUALITY: stable
  RELEASE_VERSION: ${{ github.event.inputs.version_tag }}
  SHOULD_BUILD_ZIP: ${{ github.event.inputs.build_zip == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_EXE_SYS: ${{ github.event.inputs.build_system_exe == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_EXE_USR: ${{ github.event.inputs.build_user_exe == 'true' && 'yes' || 'no' }}
  SHOULD_BUILD_MSI: ${{ github.event.inputs.build_msi == 'true' && 'yes' || 'no' }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      MS_COMMIT: ${{ env.MS_COMMIT }}
      MS_TAG: ${{ env.MS_TAG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Clone VSCode repo
        run: ./get_repo.sh

  compile:
    needs:
      - check
    runs-on: windows-2022
    permissions: {}
    defaults:
      run:
        shell: bash
    env:
      MS_COMMIT: ${{ needs.check.outputs.MS_COMMIT }}
      MS_TAG: ${{ needs.check.outputs.MS_TAG }}
      RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
      VSCODE_ARCH: x64
    outputs:
      BUILD_SOURCEVERSION: ${{ env.BUILD_SOURCEVERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Clone VSCode repo
        run: ./get_repo.sh

      - name: Build
        env:
          SHOULD_BUILD_REH: no
          SHOULD_BUILD_REH_WEB: no
        run: ./build.sh

      - name: Compress sources artifact
        run: |
          find vscode -type f -not -path "*/node_modules/*" -not -path "vscode/.build/node/*" -not -path "vscode/.git/*" > vscode.txt
          echo "vscode/.build/extensions/node_modules" >> vscode.txt
          echo "vscode/.git" >> vscode.txt
          tar -czf vscode.tar.gz -T vscode.txt

      - name: Upload sources artifact
        uses: actions/upload-artifact@v7
        with:
          name: sources
          path: ./vscode.tar.gz
          retention-days: 1

  build:
    needs:
      - check
      - compile
    runs-on: windows-2022
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        vscode_arch:
          - x64
          - arm64
    defaults:
      run:
        shell: bash
    env:
      BUILD_SOURCEVERSION: ${{ needs.compile.outputs.BUILD_SOURCEVERSION }}
      MS_COMMIT: ${{ needs.check.outputs.MS_COMMIT }}
      MS_TAG: ${{ needs.check.outputs.MS_TAG }}
      RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Download sources artifact
        uses: actions/download-artifact@v8
        with:
          name: sources

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOULD_BUILD_REH: ${{ github.event.inputs.build_reh == 'true' && 'yes' || 'no' }}
          SHOULD_BUILD_REH_WEB: ${{ github.event.inputs.build_reh == 'true' && 'yes' || 'no' }}
          npm_config_arch: ${{ matrix.vscode_arch }}
          npm_config_target_arch: ${{ matrix.vscode_arch }}
        run: ./build/windows/package.sh

      - name: Prepare assets
        env:
          SHOULD_BUILD_REH: ${{ github.event.inputs.build_reh == 'true' && 'yes' || 'no' }}
          SHOULD_BUILD_REH_WEB: ${{ github.event.inputs.build_reh == 'true' && 'yes' || 'no' }}
          SHOULD_BUILD_CLI: ${{ github.event.inputs.build_cli == 'true' && 'yes' || 'no' }}
        run: ./prepare_assets.sh

      - name: Upload assets
        uses: actions/upload-artifact@v7
        with:
          name: VSCodium-${{ matrix.vscode_arch }}
          path: assets/
          retention-days: 3
        if: ${{ github.event.inputs.upload_assets == 'true' }}

      - name: Publish assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          body: "Stable release of **VSCodium**, aligned with the version **${{ env.RELEASE_VERSION }}** of the codebase of **VSCode**."
          prerelease: false
          draft: true
          files: assets/*
        if: ${{ github.event.inputs.release_assets == 'true' }}
